
development:
  adapter: postgresql
  encoding: unicode
  database: nuedu_dev
  pool: 5
  username: nuedu
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: nuedu_test
  pool: 5
  username: postgres
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: nu-test_production
  pool: 5
  username: nu-test
  password: