default:
  plugins:
    - image
    - link
    - fullscreen
    - preview
    - textcolor
    - code
  language: "pl"
  menubar:  true
  statusbar: true
  resize: true
  height: 300
  toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | preview code | forecolor backcolor'